export const countries = [
    "United States",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo, Republic of the",
    "Congo, Democratic Republic of the",
    "Costa Rica",
    "Ivory Coast",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "North Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "St. Kitts and Nevis ",
    "St. Lucia",
    "St. Vincent and The Grenadines ",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe ",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
];

export const USstates = [{
    name: 'Alabama',
    state_code: 'AL',
  },
  {
    name: 'Alaska',
    state_code: 'AK',
  },
  {
    name: 'American Samoa',
    state_code: 'AS',
  },
  {
    name: 'Arizona',
    state_code: 'AZ',
  },
  {
    name: 'Arkansas',
    state_code: 'AR',
  },
  {
    name: 'California',
    state_code: 'CA',
  },
  {
    name: 'Colorado',
    state_code: 'CO',
  },
  {
    name: 'Connecticut',
    state_code: 'CT',
  },
  {
    name: 'Delaware',
    state_code: 'DE',
  },
  {
    name: 'District Of Columbia',
    state_code: 'DC',
  },
  {
    name: 'Federated States Of Micronesia',
    state_code: 'FM',
  },
  {
    name: 'Florida',
    state_code: 'FL',
  },
  {
    name: 'Georgia',
    state_code: 'GA',
  },
  {
    name: 'Guam Gu',
    state_code: 'GU',
  },
  {
    name: 'Hawaii',
    state_code: 'HI',
  },
  {
    name: 'Idaho',
    state_code: 'ID',
  },
  {
    name: 'Illinois',
    state_code: 'IL',
  },
  {
    name: 'Indiana',
    state_code: 'IN',
  },
  {
    name: 'Iowa',
    state_code: 'IA',
  },
  {
    name: 'Kansas',
    state_code: 'KS',
  },
  {
    name: 'Kentucky',
    state_code: 'KY',
  },
  {
    name: 'Louisiana',
    state_code: 'LA',
  },
  {
    name: 'Maine',
    state_code: 'ME',
  },
  {
    name: 'Marshall Islands',
    state_code: 'MH',
  },
  {
    name: 'Maryland',
    state_code: 'MD',
  },
  {
    name: 'Massachusetts',
    state_code: 'MA',
  },
  {
    name: 'Michigan',
    state_code: 'MI',
  },
  {
    name: 'Minnesota',
    state_code: 'MN',
  },
  {
    name: 'Mississippi',
    state_code: 'MS',
  },
  {
    name: 'Missouri',
    state_code: 'MO',
  },
  {
    name: 'Montana',
    state_code: 'MT',
  },
  {
    name: 'Nebraska',
    state_code: 'NE',
  },
  {
    name: 'Nevada',
    state_code: 'NV',
  },
  {
    name: 'New Hampshire',
    state_code: 'NH',
  },
  {
    name: 'New Jersey',
    state_code: 'NJ',
  },
  {
    name: 'New Mexico',
    state_code: 'NM',
  },
  {
    name: 'New York',
    state_code: 'NY',
  },
  {
    name: 'North Carolina',
    state_code: 'NC',
  },
  {
    name: 'North Dakota',
    state_code: 'ND',
  },
  {
    name: 'Northern Mariana Islands',
    state_code: 'MP',
  },
  {
    name: 'Ohio',
    state_code: 'OH',
  },
  {
    name: 'Oklahoma',
    state_code: 'OK',
  },
  {
    name: 'Oregon',
    state_code: 'OR',
  },
  {
    name: 'Palau',
    state_code: 'PW',
  },
  {
    name: 'Pennsylvania',
    state_code: 'PA',
  },
  {
    name: 'Puerto Rico',
    state_code: 'PR',
  },
  {
    name: 'Rhode Island',
    state_code: 'RI',
  },
  {
    name: 'South Carolina',
    state_code: 'SC',
  },
  {
    name: 'South Dakota',
    state_code: 'SD',
  },
  {
    name: 'Tennessee',
    state_code: 'TN',
  },
  {
    name: 'Texas',
    state_code: 'TX',
  },
  {
    name: 'Utah',
    state_code: 'UT',
  },
  {
    name: 'Vermont',
    state_code: 'VT',
  },
  {
    name: 'Virgin Islands',
    state_code: 'VI',
  },
  {
    name: 'Virginia',
    state_code: 'VA',
  },
  {
    name: 'Washington',
    state_code: 'WA',
  },
  {
    name: 'West Virginia',
    state_code: 'WV',
  },
  {
    name: 'Wisconsin',
    state_code: 'WI',
  },
  {
    name: 'Wyoming',
    state_code: 'WY',
  },
  ];
  